import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f4f4f4',
  },
  innerContainer: {
    flex: 1,
    padding: 5,
    paddingTop: 40,
    backgroundColor: '#fff',
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 7,
    marginBottom: 15,
  },
  bemVindoText: {
    fontSize: 20,
    fontWeight: '600',
    color: '#333',
    marginBottom: 20,
    textAlign: 'center',
  },
  totalDespesasContainer: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 20,
    marginBottom: 25,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 7,
  },
  totalDespesasTitle: {
    fontSize: 18,
    fontWeight: '500',
    color: '#555',
  },
  totalDespesasValue: {
    fontSize: 28,
    fontWeight: '700',
    color: '#1E8187',
    marginTop: 8,
    textAlign: 'center',
  },
  listaDespesasContainer: {
    width: '100%',
  },
  botaoContainer: {
    position: 'absolute',
    bottom: 20,
    right: 20,
    width: 60,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 40,
    backgroundColor: '#1E8187',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 7,
  },
});
